# Generated by Django 4.1.3 on 2022-11-27 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumsubcategories',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
