# Generated by Django 4.1.3 on 2022-12-01 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_alter_forumcategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumsubcategories',
            name='slug',
            field=models.SlugField(default='none', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='forumtopic',
            name='slug',
            field=models.SlugField(default='none', unique=True),
            preserve_default=False,
        ),
    ]
