# Generated by Django 4.1.3 on 2022-11-27 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_alter_forumsubcategories_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumsubcategories',
            name='logo',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
