# Generated by Django 4.1.3 on 2022-12-01 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_alter_forumsubcategories_slug_alter_forumtopic_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumcategory',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='forumsubcategories',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='forumtopic',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
