# Generated by Django 4.1.3 on 2022-11-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_remove_forumsubcategories_logo_forumcategory_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumcategory',
            name='logo',
            field=models.ImageField(default='', upload_to='forum/static_images'),
        ),
    ]
