# Generated by Django 4.1.3 on 2022-12-16 15:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('forum', '0005_forumcategory_date_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumcategory',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='forumsubcategories',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='forumtopic',
            name='date_created',
        ),
    ]
