# Generated by Django 4.1.3 on 2022-12-14 09:50

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.RegexValidator('^[a-zA-z0-9_-]+$', message='Ensure this value contains only letters, numbers, underscore and dashes.')])),
                ('first_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.RegexValidator('^[a-zA-z]+$', message='Ensure this value contains only letters and numbers.')])),
                ('last_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.RegexValidator('^[a-zA-z]+$', message='Ensure this value contains only letters and numbers.')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('donotshow', "DO no't show")], max_length=9)),
                ('age', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(12), django.core.validators.RegexValidator('^\\d+$', message='Ensure this value contains only numbers.')])),
                ('avatar_pic', models.ImageField(blank=True, default='/media/avatars_icon.png', null=True, upload_to='')),
                ('signature', models.TextField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AboutData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileModel',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('donotshow', "DO no't show")], max_length=9)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(12), django.core.validators.RegexValidator('^\\d+$', message='Ensure this value contains only numbers.')])),
                ('avatar_pic', models.URLField()),
                ('signature', models.TextField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
