# Generated by Django 4.1.3 on 2022-12-14 14:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='first_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2),
                                                              django.core.validators.RegexValidator('^[a-zA-z]+$',
                                                                                                    message='Ensure this value contains only letters.')]),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='last_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2),
                                                              django.core.validators.RegexValidator('^[a-zA-z]+$',
                                                                                                    message='Ensure this value contains only letters.')]),
        ),
    ]
