# Generated by Django 4.1.3 on 2022-12-01 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='avatar_pic',
            field=models.URLField(blank=True, default='/static/users/img/avatars_icon.png', null=True),
        ),
    ]
