# Generated by Django 4.1.3 on 2022-11-27 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemodel',
            name='signature',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
