# Generated by Django 4.1.3 on 2022-11-28 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofilemodel_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemodel',
            name='city',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
