# Generated by Django 4.1.3 on 2022-12-16 13:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_appuser_first_name_alter_appuser_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('description', models.TextField()),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('characteristics', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('appuser', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
