# Generated by Django 4.1.3 on 2022-11-29 12:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofilemodel_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='age',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(12), django.core.validators.RegexValidator('^\\d+$', message='Ensure this value contains only numbers.')]),
        ),
        migrations.AddField(
            model_name='appuser',
            name='avatar_pic',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='city',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('donotshow', "DO no't show")], default='Male', max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appuser',
            name='signature',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
