# Generated by Django 4.1.3 on 2022-12-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_appuser_avatar_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='avatar_pic',
            field=models.ImageField(blank=True, default='/media/avatars_icon.png', null=True, upload_to=''),
        ),
    ]
