# Generated by Django 4.1.3 on 2022-12-16 20:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0004_remove_catinfo_appuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='catinfo',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='catinfo',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='catinfo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
